[package]
name = "mc_art_adder"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.24", features = ["png", "jpeg"] }
rand = "0.9.2"
rayon = "1.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
